use crate::tables::{SdtHeader, SdtSignature};

#[derive(Debug, Clone, Copy)]
pub struct Fadt {
    pub header: SdtHeader,
    pub sci_command: u32,
    pub smi_command_port: u32,
    pub acpi_enable: u8,
    pub acpi_disable: u8,
    pub s4bios_req: u8,
    pub pstate_cnt: u8,
    pub pm1a_evt_blk: u32,
    pub pm1b_evt_blk: u32,
    pub pm1a_cnt_blk: u32,
    pub pm1b_cnt_blk: u32,
    pub pm2_cnt_blk: u32,
    pub pm_tmr_blk: u32,
    pub gpe0_blk: u32,
    pub gpe1_blk: u32,
    pub pm1_evt_len: u8,
    pub pm1_cnt_len: u8,
    pub pm2_cnt_len: u8,
    pub pm_tmr_len: u8,
    pub gpe0_blk_len: u8,
    pub gpe1_blk_len: u8,
    pub gpe1_base: u8,
    pub cst_cnt: u8,
    pub p_lvl2_lat: u16,
    pub p_lvl3_lat: u16,
    pub flush_size: u16,
    pub flush_stride: u16,
    pub duty_offset: u8,
    pub duty_width: u8,
    pub day_alrm: u8,
    pub mon_alrm: u8,
    pub century: u8,
    pub iapc_boot_arch: u16,
    pub reserved: u8,
    pub flags: u32,
    pub reset_reg: [u8; 12],
    pub reset_value: u8,
    pub arm_boot_arch: u16,
    pub fadt_minor_version: u8,
    pub x_firmware_ctrl: u64,
    pub x_dsdt: u64,
    pub x_pm1a_evt_blk: [u8; 12],
    pub x_pm1b_evt_blk: [u8; 12],
    pub x_pm1a_cnt_blk: [u8; 12],
    pub x_pm1b_cnt_blk: [u8; 12],
    pub x_pm2_cnt_blk: [u8; 12],
    pub x_pm_tmr_blk: [u8; 12],
    pub x_gpe0_blk: [u8; 12],
    pub x_gpe1_blk: [u8; 12],
    pub sleep_control_reg: [u8; 12],
    pub sleep_status_reg: [u8; 12],
    pub hypervisor_vendor_id: u64,
}

impl Fadt {
    pub fn from_bytes(data: &[u8]) -> Option<Self> {
        let header = SdtHeader::from_bytes(data)?;
        if header.signature != SdtSignature::FADT { return None; }
        if data.len() < 244 { return None; }
        Some(Self {
            header,
            sci_command: u32::from_le_bytes([data[36], data[37], data[38], data[39]]),
            smi_command_port: u32::from_le_bytes([data[40], data[41], data[42], data[43]]),
            acpi_enable: data[44],
            acpi_disable: data[45],
            s4bios_req: data[46],
            pstate_cnt: data[47],
            pm1a_evt_blk: u32::from_le_bytes([data[48], data[49], data[50], data[51]]),
            pm1b_evt_blk: u32::from_le_bytes([data[52], data[53], data[54], data[55]]),
            pm1a_cnt_blk: u32::from_le_bytes([data[56], data[57], data[58], data[59]]),
            pm1b_cnt_blk: u32::from_le_bytes([data[60], data[61], data[62], data[63]]),
            pm2_cnt_blk: u32::from_le_bytes([data[64], data[65], data[66], data[67]]),
            pm_tmr_blk: u32::from_le_bytes([data[68], data[69], data[70], data[71]]),
            gpe0_blk: u32::from_le_bytes([data[72], data[73], data[74], data[75]]),
            gpe1_blk: u32::from_le_bytes([data[76], data[77], data[78], data[79]]),
            pm1_evt_len: data[80],
            pm1_cnt_len: data[81],
            pm2_cnt_len: data[82],
            pm_tmr_len: data[83],
            gpe0_blk_len: data[84],
            gpe1_blk_len: data[85],
            gpe1_base: data[86],
            cst_cnt: data[87],
            p_lvl2_lat: u16::from_le_bytes([data[88], data[89]]),
            p_lvl3_lat: u16::from_le_bytes([data[90], data[91]]),
            flush_size: u16::from_le_bytes([data[92], data[93]]),
            flush_stride: u16::from_le_bytes([data[94], data[95]]),
            duty_offset: data[96],
            duty_width: data[97],
            day_alrm: data[98],
            mon_alrm: data[99],
            century: data[100],
            iapc_boot_arch: u16::from_le_bytes([data[101], data[102]]),
            reserved: data[103],
            flags: u32::from_le_bytes([data[104], data[105], data[106], data[107]]),
            reset_reg: {
                let mut r = [0u8; 12]; r.copy_from_slice(&data[108..120]); r
            },
            reset_value: data[120],
            arm_boot_arch: u16::from_le_bytes([data[121], data[122]]),
            fadt_minor_version: data[123],
            x_firmware_ctrl: u64::from_le_bytes([data[124], data[125], data[126], data[127], data[128], data[129], data[130], data[131]]),
            x_dsdt: u64::from_le_bytes([data[132], data[133], data[134], data[135], data[136], data[137], data[138], data[139]]),
            x_pm1a_evt_blk: { let mut r = [0u8; 12]; r.copy_from_slice(&data[140..152]); r },
            x_pm1b_evt_blk: { let mut r = [0u8; 12]; r.copy_from_slice(&data[152..164]); r },
            x_pm1a_cnt_blk: { let mut r = [0u8; 12]; r.copy_from_slice(&data[164..176]); r },
            x_pm1b_cnt_blk: { let mut r = [0u8; 12]; r.copy_from_slice(&data[176..188]); r },
            x_pm2_cnt_blk: { let mut r = [0u8; 12]; r.copy_from_slice(&data[188..200]); r },
            x_pm_tmr_blk: { let mut r = [0u8; 12]; r.copy_from_slice(&data[200..212]); r },
            x_gpe0_blk: { let mut r = [0u8; 12]; r.copy_from_slice(&data[212..224]); r },
            x_gpe1_blk: { let mut r = [0u8; 12]; if data.len() >= 236 { r.copy_from_slice(&data[224..236]); } r },
            sleep_control_reg: { let mut r = [0u8; 12]; if data.len() >= 248 { r.copy_from_slice(&data[236..248]); } r },
            sleep_status_reg: { let mut r = [0u8; 12]; if data.len() >= 260 { r.copy_from_slice(&data[248..260]); } r },
            hypervisor_vendor_id: if data.len() >= 268 {
                u64::from_le_bytes([data[260], data[261], data[262], data[263], data[264], data[265], data[266], data[267]])
            } else { 0 },
        })
    }

    pub fn dsdt_phys(&self) -> u64 {
        if self.x_dsdt != 0 { self.x_dsdt } else { self.header.length as u64 }
    }
}
