[package]
name = "cluu-edit"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "edit"
path = "src/main.rs"

[dependencies]
libcluu = { path = "../libcluu", features = ["posix"] }
libtui = { package = "cluu-libtui", path = "../libtui", features = ["runtime"] }
postcard = { workspace = true }
cluu_wire = { path = "../cluu_wire" }
