[package]
name = "cluu-shell"
version = "0.1.0"
edition = "2021"
description = "CLUU interactive shell"
authors = ["CLUU Team", "Balazs Valkony"]
license = "MIT"

[dependencies]
libcluu = { path = "../libcluu", features = ["posix"] }
cluu_wire = { path = "../cluu_wire" }
cluu_lang = { path = "../../crates/cluu_lang", optional = true }

[features]
default = ["lang-parser"]
lang-parser = ["cluu_lang"]
debug-shellcrash = []

[[bin]]
name = "shell"
path = "src/main.rs"
