[[service]]
image = "console"

[[service]]
image = "vtmgr"

[[service]]
image = "kbd"

[[service]]
image = "compositor"
session_mode = 0

[[service]]
image = "login"

[[service]]
image = "getty"
args = ["/dev/tty1"]

[[service]]
image = "getty"
args = ["/dev/tty2"]

[[service]]
image = "getty"
args = ["/dev/tty3"]