use fontdue::{Font, FontSettings};
use std::io::Write;

fn main() {
    println!("cargo:rerun-if-changed=fonts/0xProto-Regular.ttf");
    println!("cargo:rerun-if-changed=fonts/0xProto-Bold.ttf");
    println!("cargo:rerun-if-changed=fonts/0xProto-Italic.ttf");

    let regular = Font::from_bytes(
        &include_bytes!("fonts/0xProto-Regular.ttf")[..],
        FontSettings::default(),
    )
    .expect("failed to parse 0xProto-Regular.ttf");
    let bold = Font::from_bytes(
        &include_bytes!("fonts/0xProto-Bold.ttf")[..],
        FontSettings::default(),
    )
    .expect("failed to parse 0xProto-Bold.ttf");
    let italic = Font::from_bytes(
        &include_bytes!("fonts/0xProto-Italic.ttf")[..],
        FontSettings::default(),
    )
    .expect("failed to parse 0xProto-Italic.ttf");

    let cp437 = cp437_to_unicode();

    let regular_data = rasterize_font(&regular, &cp437);
    let bold_data = rasterize_font(&bold, &cp437);
    let italic_data = rasterize_font(&italic, &cp437);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = std::path::Path::new(&out_dir).join("font_0xproto.rs");
    let mut file = std::fs::File::create(&out_path).expect("failed to create font_0xproto.rs");

    writeln!(file, "// Auto-generated by build.rs from 0xProto v2.502 (OFL-1.1)").unwrap();
    writeln!(file, "// 256 glyphs x 128 bytes (8-bit alpha, 8x16) = 32768 bytes per variant").unwrap();
    writeln!(file).unwrap();

    write_font_array(&mut file, "FONT_0XPROTO_REGULAR_ALPHA", &regular_data);
    write_font_array(&mut file, "FONT_0XPROTO_BOLD_ALPHA", &bold_data);
    write_font_array(&mut file, "FONT_0XPROTO_ITALIC_ALPHA", &italic_data);

    write_srgb_luts();
}

fn write_srgb_luts() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");

    let srgb_to_linear: [u32; 256] = {
        let mut lut = [0u32; 256];
        for i in 0..256u32 {
            let c = i as f64 / 255.0;
            let lin = if c <= 0.04045 {
                c / 12.92
            } else {
                ((c + 0.055) / 1.055).powf(2.4)
            };
            lut[i as usize] = (lin * 255.0).round() as u32;
        }
        lut
    };

    let linear_to_srgb: [u8; 256] = {
        let mut lut = [0u8; 256];
        for i in 0..256u32 {
            let c = i as f64 / 255.0;
            let srgb = if c <= 0.0031308 {
                c * 12.92
            } else {
                1.055 * c.powf(1.0 / 2.4) - 0.055
            };
            lut[i as usize] = (srgb * 255.0).round().clamp(0.0, 255.0) as u8;
        }
        lut
    };

    let srgb_path = std::path::Path::new(&out_dir).join("srgb_lut.rs");
    let mut f = std::fs::File::create(&srgb_path).expect("failed to create srgb_lut.rs");
    write!(f, "[").unwrap();
    for (i, &v) in srgb_to_linear.iter().enumerate() {
        if i % 16 == 0 { writeln!(f).unwrap(); }
        write!(f, "{},", v).unwrap();
    }
    writeln!(f, "]").unwrap();

    let lin_path = std::path::Path::new(&out_dir).join("linear_srgb_lut.rs");
    let mut f = std::fs::File::create(&lin_path).expect("failed to create linear_srgb_lut.rs");
    write!(f, "[").unwrap();
    for (i, &v) in linear_to_srgb.iter().enumerate() {
        if i % 16 == 0 { writeln!(f).unwrap(); }
        write!(f, "{},", v).unwrap();
    }
    writeln!(f, "]").unwrap();
}

const GLYPH_W: usize = 8;
const GLYPH_H: usize = 16;
const GLYPH_ALPHA_SIZE: usize = GLYPH_W * GLYPH_H;
const FONT_SIZE: f32 = 13.5;
const BASELINE: i32 = 13;

fn rasterize_font(font: &Font, cp437: &[char; 256]) -> [u8; 32768] {
    let mut result = [0u8; 32768];

    for (i, &ch) in cp437.iter().enumerate() {
        if (0xB0..=0xDF).contains(&(i as u8)) {
            continue;
        }

        let (metrics, bitmap) = font.rasterize(ch, FONT_SIZE);
        let gw = metrics.width;
        let gh = metrics.height as i32;
        if gw == 0 || gh == 0 {
            continue;
        }

        let x_start = if metrics.xmin > 0 { metrics.xmin as usize } else { 0 };
        let y_start = BASELINE - metrics.ymin - gh;

        for row in 0..gh {
            let cell_row = y_start + row;
            if cell_row < 0 || cell_row >= GLYPH_H as i32 {
                continue;
            }
            for col in 0..gw {
                let cell_col = x_start + col;
                if cell_col >= GLYPH_W {
                    break;
                }
                let alpha = bitmap[(row as usize) * gw + col];
                result[i * GLYPH_ALPHA_SIZE + (cell_row as usize) * GLYPH_W + cell_col] = alpha;
            }
        }
    }
    result
}

fn write_font_array(file: &mut std::fs::File, name: &str, data: &[u8; 32768]) {
    write!(file, "pub const {}: [u8; 32768] = [", name).unwrap();
    for (i, &byte) in data.iter().enumerate() {
        if i % 16 == 0 {
            writeln!(file).unwrap();
            write!(file, "    ").unwrap();
        }
        write!(file, "0x{:02x},", byte).unwrap();
    }
    writeln!(file, "\n];").unwrap();
    writeln!(file).unwrap();
}

fn cp437_to_unicode() -> [char; 256] {
    [
        '\0', '☺', '☻', '♥', '♦', '♣', '♠', '•', '◘', '○', '◙', '♂', '♀', '♪', '♫', '☼',
        '►', '◄', '↕', '‼', '¶', '§', '▬', '↨', '↑', '↓', '→', '←', '∟', '↔', '▲', '▼',
        ' ', '!', '"', '#', '$', '%', '&', '\'', '(', ')', '*', '+', ',', '-', '.', '/',
        '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?',
        '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O',
        'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '^', '_',
        '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o',
        'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~', '⌂',
        'Ç', 'ü', 'é', 'â', 'ä', 'à', 'å', 'ç', 'ê', 'ë', 'è', 'ï', 'î', 'ì', 'Ä', 'Å',
        'É', 'æ', 'Æ', 'ô', 'ö', 'ò', 'û', 'ù', 'ÿ', 'Ö', 'Ü', '¢', '£', '¥', '₧', 'ƒ',
        'á', 'í', 'ó', 'ú', 'ñ', 'Ñ', 'ª', 'º', '¿', '⌐', '¬', '½', '¼', '¡', '«', '»',
        '░', '▒', '▓', '│', '┤', '╡', '╢', '╖', '╕', '╣', '║', '╗', '╝', '╜', '╛', '┐',
        '└', '┴', '┬', '├', '─', '┼', '╞', '╟', '╚', '╔', '╩', '╦', '╠', '═', '╬', '╧',
        '╨', '╤', '╥', '╙', '╘', '╒', '╓', '╫', '╪', '┘', '┌', '█', '▄', '▌', '▐', '▀',
        'α', 'ß', 'Γ', 'π', 'Σ', 'σ', 'µ', 'τ', 'Φ', 'Θ', 'Ω', 'δ', '∞', 'φ', 'ε', '∩',
        '≡', '±', '≥', '≤', '⌠', '⌡', '÷', '≈', '°', '∙', '·', '√', 'ⁿ', '²', '■', '\0',
    ]
}
