use fontdue::{Font, FontSettings};
use std::io::Write;

fn main() {
    println!("cargo:rerun-if-changed=fonts/0xProto-Regular.ttf");
    println!("cargo:rerun-if-changed=fonts/0xProto-Bold.ttf");
    println!("cargo:rerun-if-changed=fonts/0xProto-Italic.ttf");

    let regular = Font::from_bytes(
        &include_bytes!("fonts/0xProto-Regular.ttf")[..],
        FontSettings::default(),
    )
    .expect("failed to parse 0xProto-Regular.ttf");
    let bold = Font::from_bytes(
        &include_bytes!("fonts/0xProto-Bold.ttf")[..],
        FontSettings::default(),
    )
    .expect("failed to parse 0xProto-Bold.ttf");
    let italic = Font::from_bytes(
        &include_bytes!("fonts/0xProto-Italic.ttf")[..],
        FontSettings::default(),
    )
    .expect("failed to parse 0xProto-Italic.ttf");

    let cp437 = cp437_to_unicode();

    let regular_data = rasterize_font(&regular, &cp437);
    let bold_data = rasterize_font(&bold, &cp437);
    let italic_data = rasterize_font(&italic, &cp437);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = std::path::Path::new(&out_dir).join("font_0xproto.rs");
    let mut file = std::fs::File::create(&out_path).expect("failed to create font_0xproto.rs");

    writeln!(file, "// Auto-generated by build.rs from 0xProto v2.502 (OFL-1.1)").unwrap();
    writeln!(file, "// 256 glyphs x 128 bytes (8-bit alpha, 8x16) = 32768 bytes per variant").unwrap();
    writeln!(file).unwrap();

    write_font_array(&mut file, "FONT_0XPROTO_REGULAR_ALPHA", &regular_data);
    write_font_array(&mut file, "FONT_0XPROTO_BOLD_ALPHA", &bold_data);
    write_font_array(&mut file, "FONT_0XPROTO_ITALIC_ALPHA", &italic_data);

    // ── Unicode extension banks ─────────────────────────────────────────
    //
    // Three new glyph banks covering Box Drawing (U+2500-U+257F),
    // Block Elements (U+2580-U+259F), and Braille Patterns (U+2800-U+28FF).
    //
    // Box Drawing is rasterized from 0xProto (which has full 128/128
    // coverage). Block Elements and Braille are generated programmatically
    // (0xProto has zero coverage for both; the shapes are geometric).
    // Block and Braille are weight-independent (filled rectangles / dots),
    // so only one bank each is emitted.

    let box_reg  = rasterize_range(&regular, 0x2500..=0x257F);
    let box_bold = rasterize_range(&bold,    0x2500..=0x257F);
    let box_ital = rasterize_range(&italic,  0x2500..=0x257F);

    let block   = generate_block_elements();
    let braille = generate_braille();

    let ext_path = std::path::Path::new(&out_dir).join("font_unicode_ext.rs");
    let mut ext_file = std::fs::File::create(&ext_path).expect("failed to create font_unicode_ext.rs");

    write_font_slice(&mut ext_file, "FONT_BOX_REGULAR_ALPHA", &box_reg);
    write_font_slice(&mut ext_file, "FONT_BOX_BOLD_ALPHA", &box_bold);
    write_font_slice(&mut ext_file, "FONT_BOX_ITALIC_ALPHA", &box_ital);
    write_font_slice(&mut ext_file, "FONT_BLOCK_ALPHA", &block);
    write_font_slice(&mut ext_file, "FONT_BRAILLE_ALPHA", &braille);

    write_srgb_luts();
}

fn write_srgb_luts() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");

    let srgb_to_linear: [u32; 256] = {
        let mut lut = [0u32; 256];
        for i in 0..256u32 {
            let c = i as f64 / 255.0;
            let lin = if c <= 0.04045 {
                c / 12.92
            } else {
                ((c + 0.055) / 1.055).powf(2.4)
            };
            lut[i as usize] = (lin * 255.0).round() as u32;
        }
        lut
    };

    let linear_to_srgb: [u8; 256] = {
        let mut lut = [0u8; 256];
        for i in 0..256u32 {
            let c = i as f64 / 255.0;
            let srgb = if c <= 0.0031308 {
                c * 12.92
            } else {
                1.055 * c.powf(1.0 / 2.4) - 0.055
            };
            lut[i as usize] = (srgb * 255.0).round().clamp(0.0, 255.0) as u8;
        }
        lut
    };

    let srgb_path = std::path::Path::new(&out_dir).join("srgb_lut.rs");
    let mut f = std::fs::File::create(&srgb_path).expect("failed to create srgb_lut.rs");
    write!(f, "[").unwrap();
    for (i, &v) in srgb_to_linear.iter().enumerate() {
        if i % 16 == 0 { writeln!(f).unwrap(); }
        write!(f, "{},", v).unwrap();
    }
    writeln!(f, "]").unwrap();

    let lin_path = std::path::Path::new(&out_dir).join("linear_srgb_lut.rs");
    let mut f = std::fs::File::create(&lin_path).expect("failed to create linear_srgb_lut.rs");
    write!(f, "[").unwrap();
    for (i, &v) in linear_to_srgb.iter().enumerate() {
        if i % 16 == 0 { writeln!(f).unwrap(); }
        write!(f, "{},", v).unwrap();
    }
    writeln!(f, "]").unwrap();
}

const GLYPH_W: usize = 8;
const GLYPH_H: usize = 16;
const GLYPH_ALPHA_SIZE: usize = GLYPH_W * GLYPH_H;
const FONT_SIZE: f32 = 13.5;
const BASELINE: i32 = 13;

fn rasterize_font(font: &Font, cp437: &[char; 256]) -> [u8; 32768] {
    let mut result = [0u8; 32768];

    for (i, &ch) in cp437.iter().enumerate() {
        if (0xB0..=0xDF).contains(&(i as u8)) {
            continue;
        }

        let (metrics, bitmap) = font.rasterize(ch, FONT_SIZE);
        let gw = metrics.width;
        let gh = metrics.height as i32;
        if gw == 0 || gh == 0 {
            continue;
        }

        let x_start = if metrics.xmin > 0 { metrics.xmin as usize } else { 0 };
        let y_start = BASELINE - metrics.ymin - gh;

        for row in 0..gh {
            let cell_row = y_start + row;
            if cell_row < 0 || cell_row >= GLYPH_H as i32 {
                continue;
            }
            for col in 0..gw {
                let cell_col = x_start + col;
                if cell_col >= GLYPH_W {
                    break;
                }
                let alpha = bitmap[(row as usize) * gw + col];
                result[i * GLYPH_ALPHA_SIZE + (cell_row as usize) * GLYPH_W + cell_col] = alpha;
            }
        }
    }
    result
}

fn rasterize_range(font: &Font, range: std::ops::RangeInclusive<u32>) -> Vec<u8> {
    let count = (range.end() - range.start() + 1) as usize;
    let mut result = vec![0u8; count * GLYPH_ALPHA_SIZE];
    for (i, cp) in range.enumerate() {
        let ch = char::from_u32(cp).unwrap_or('\0');
        let (metrics, bitmap) = font.rasterize(ch, FONT_SIZE);
        let gw = metrics.width;
        let gh = metrics.height as i32;
        if gw == 0 || gh == 0 {
            continue;
        }
        let x_start = if metrics.xmin > 0 { metrics.xmin as usize } else { 0 };
        let y_start = BASELINE - metrics.ymin - gh;
        for row in 0..gh {
            let cell_row = y_start + row;
            if cell_row < 0 || cell_row >= GLYPH_H as i32 {
                continue;
            }
            for col in 0..gw {
                let cell_col = x_start + col;
                if cell_col >= GLYPH_W {
                    break;
                }
                let alpha = bitmap[(row as usize) * gw + col];
                result[i * GLYPH_ALPHA_SIZE + (cell_row as usize) * GLYPH_W + cell_col] = alpha;
            }
        }
    }
    result
}

fn generate_block_elements() -> Vec<u8> {
    let mut out = vec![0u8; 32 * GLYPH_ALPHA_SIZE];
    for cp in 0x2580u32..=0x259F {
        let idx = ((cp - 0x2580) as usize) * GLYPH_ALPHA_SIZE;
        let glyph = &mut out[idx..idx + GLYPH_ALPHA_SIZE];
        match cp {
            0x2580 => fill_rows(glyph, 0, 8),
            0x2581 => fill_rows(glyph, 14, 16),
            0x2582 => fill_rows(glyph, 12, 16),
            0x2583 => fill_rows(glyph, 10, 16),
            0x2584 => fill_rows(glyph, 8, 16),
            0x2585 => fill_rows(glyph, 6, 16),
            0x2586 => fill_rows(glyph, 4, 16),
            0x2587 => fill_rows(glyph, 2, 16),
            0x2588 => fill_rows(glyph, 0, 16),
            0x2589 => fill_cols_rows(glyph, 0, 7, 0, 16),
            0x258A => fill_cols_rows(glyph, 0, 6, 0, 16),
            0x258B => fill_cols_rows(glyph, 0, 5, 0, 16),
            0x258C => fill_cols_rows(glyph, 0, 4, 0, 16),
            0x258D => fill_cols_rows(glyph, 0, 3, 0, 16),
            0x258E => fill_cols_rows(glyph, 0, 2, 0, 16),
            0x258F => fill_cols_rows(glyph, 0, 1, 0, 16),
            0x2590 => fill_cols_rows(glyph, 4, 8, 0, 16),
            0x2591 => fill_dither(glyph, 0x25),
            0x2592 => fill_dither(glyph, 0x50),
            0x2593 => fill_dither(glyph, 0x75),
            0x2594 => fill_rows(glyph, 0, 2),
            0x2595 => fill_cols_rows(glyph, 7, 8, 0, 16),
            0x2596 => fill_cols_rows(glyph, 0, 4, 8, 16),
            0x2597 => fill_cols_rows(glyph, 4, 8, 8, 16),
            0x2598 => fill_cols_rows(glyph, 0, 4, 0, 8),
            0x2599 => {
                fill_cols_rows(glyph, 0, 4, 0, 8);
                fill_rows(glyph, 8, 16);
            }
            0x259A => {
                fill_cols_rows(glyph, 0, 4, 0, 8);
                fill_cols_rows(glyph, 4, 8, 8, 16);
            }
            0x259B => {
                fill_rows(glyph, 0, 8);
                fill_cols_rows(glyph, 0, 4, 8, 16);
            }
            0x259C => {
                fill_rows(glyph, 0, 8);
                fill_cols_rows(glyph, 4, 8, 8, 16);
            }
            0x259D => fill_cols_rows(glyph, 4, 8, 0, 8),
            0x259E => {
                fill_cols_rows(glyph, 4, 8, 0, 8);
                fill_cols_rows(glyph, 0, 4, 8, 16);
            }
            0x259F => {
                fill_cols_rows(glyph, 4, 8, 0, 8);
                fill_rows(glyph, 8, 16);
            }
            _ => {}
        }
    }
    out
}

// Dot positions (top-left corner of 2×2 dot) indexed by Unicode Braille
// bit number. 2 columns × 4 rows in the 8×16 cell:
//   col 0 at x=1, col 1 at x=5  (4px apart, 2px from cell edges)
//   row 0 at y=1, row 1 at y=5, row 2 at y=9, row 3 at y=13
fn generate_braille() -> Vec<u8> {
    const DOT_POSITIONS: [(usize, usize); 8] = [
        (1, 1), (1, 5), (1, 9), (5, 1),
        (5, 5), (5, 9), (1, 13), (5, 13),
    ];
    let mut out = vec![0u8; 256 * GLYPH_ALPHA_SIZE];
    for cp in 0x2800u32..=0x28FF {
        let bits = (cp - 0x2800) as u8;
        let idx = ((cp - 0x2800) as usize) * GLYPH_ALPHA_SIZE;
        let glyph = &mut out[idx..idx + GLYPH_ALPHA_SIZE];
        for bit in 0..8 {
            if (bits >> bit) & 1 != 0 {
                let (cx, cy) = DOT_POSITIONS[bit];
                for dy in 0..2 {
                    for dx in 0..2 {
                        let x = cx + dx;
                        let y = cy + dy;
                        if x < GLYPH_W && y < GLYPH_H {
                            glyph[y * GLYPH_W + x] = 255;
                        }
                    }
                }
            }
        }
    }
    out
}

fn fill_rows(glyph: &mut [u8], y0: usize, y1: usize) {
    for y in y0..y1 {
        for x in 0..GLYPH_W {
            glyph[y * GLYPH_W + x] = 255;
        }
    }
}

fn fill_cols_rows(glyph: &mut [u8], x0: usize, x1: usize, y0: usize, y1: usize) {
    for y in y0..y1 {
        for x in x0..x1 {
            glyph[y * GLYPH_W + x] = 255;
        }
    }
}

fn fill_dither(glyph: &mut [u8], density: u8) {
    let pattern: [[u8; 2]; 2] = match density {
        0x25 => [[255, 0], [0, 0]],
        0x50 => [[255, 0], [0, 255]],
        0x75 => [[255, 255], [255, 0]],
        _ => [[0; 2]; 2],
    };
    for y in 0..GLYPH_H {
        for x in 0..GLYPH_W {
            glyph[y * GLYPH_W + x] = pattern[y % 2][x % 2];
        }
    }
}

fn write_font_slice(file: &mut std::fs::File, name: &str, data: &[u8]) {
    write!(file, "pub const {}: [u8; {}] = [", name, data.len()).unwrap();
    for (i, &byte) in data.iter().enumerate() {
        if i % 16 == 0 {
            writeln!(file).unwrap();
            write!(file, "    ").unwrap();
        }
        write!(file, "0x{:02x},", byte).unwrap();
    }
    writeln!(file, "\n];").unwrap();
    writeln!(file).unwrap();
}

fn write_font_array(file: &mut std::fs::File, name: &str, data: &[u8; 32768]) {
    write!(file, "pub const {}: [u8; 32768] = [", name).unwrap();
    for (i, &byte) in data.iter().enumerate() {
        if i % 16 == 0 {
            writeln!(file).unwrap();
            write!(file, "    ").unwrap();
        }
        write!(file, "0x{:02x},", byte).unwrap();
    }
    writeln!(file, "\n];").unwrap();
    writeln!(file).unwrap();
}

fn cp437_to_unicode() -> [char; 256] {
    [
        '\0', '☺', '☻', '♥', '♦', '♣', '♠', '•', '◘', '○', '◙', '♂', '♀', '♪', '♫', '☼',
        '►', '◄', '↕', '‼', '¶', '§', '▬', '↨', '↑', '↓', '→', '←', '∟', '↔', '▲', '▼',
        ' ', '!', '"', '#', '$', '%', '&', '\'', '(', ')', '*', '+', ',', '-', '.', '/',
        '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?',
        '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O',
        'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '^', '_',
        '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o',
        'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~', '⌂',
        'Ç', 'ü', 'é', 'â', 'ä', 'à', 'å', 'ç', 'ê', 'ë', 'è', 'ï', 'î', 'ì', 'Ä', 'Å',
        'É', 'æ', 'Æ', 'ô', 'ö', 'ò', 'û', 'ù', 'ÿ', 'Ö', 'Ü', '¢', '£', '¥', '₧', 'ƒ',
        'á', 'í', 'ó', 'ú', 'ñ', 'Ñ', 'ª', 'º', '¿', '⌐', '¬', '½', '¼', '¡', '«', '»',
        '░', '▒', '▓', '│', '┤', '╡', '╢', '╖', '╕', '╣', '║', '╗', '╝', '╜', '╛', '┐',
        '└', '┴', '┬', '├', '─', '┼', '╞', '╟', '╚', '╔', '╩', '╦', '╠', '═', '╬', '╧',
        '╨', '╤', '╥', '╙', '╘', '╒', '╓', '╫', '╪', '┘', '┌', '█', '▄', '▌', '▐', '▀',
        'α', 'ß', 'Γ', 'π', 'Σ', 'σ', 'µ', 'τ', 'Φ', 'Θ', 'Ω', 'δ', '∞', 'φ', 'ε', '∩',
        '≡', '±', '≥', '≤', '⌠', '⌡', '÷', '≈', '°', '∙', '·', '√', 'ⁿ', '²', '■', '\0',
    ]
}
