[package]
name = "cluu-init"
version = "0.1.0"
edition = "2021"
description = "CLUU init process"
authors = ["CLUU Team", "Balazs Valkony"]
license = "MIT"

[dependencies]
libcluu = { path = "../libcluu" }
cluu-root-procmgr = { path = "../root-procmgr" }
klibcluu = { path = "../../klibcluu" }

[[bin]]
name = "init"
path = "src/main.rs"
