[package]
name = "cluu-kbd"
version = "0.1.0"
edition = "2021"
description = "CLUU keyboard service"
authors = ["CLUU Team", "Balazs Valkony"]
license = "MIT"

[dependencies]
libcluu = { path = "../libcluu" }

[features]
default = ["hu-layout"]
hu-layout = []
us-layout = []

[[bin]]
name = "kbd"
path = "src/main.rs"
