[package]
name = "cluu-root-procmgr"
version = "0.1.0"
edition = "2021"
description = "CLUU process manager server"
authors = ["CLUU Team", "Balazs Valkony"]
license = "MIT"

[dependencies]
libcluu = { path = "../libcluu" }
cluu_wire = { path = "../cluu_wire" }
procmgr-common = { path = "../libs/procmgr-common" }
spin = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
libcluu = { path = "../libcluu", features = ["host-test"] }
proptest = { workspace = true }

[features]
default = []
host-test = ["libcluu/host-test", "procmgr-common/host-test"]  # enables std for unit tests on host

[lib]
name = "root_procmgr"
path = "src/lib.rs"

[[bin]]
name = "root-procmgr"
path = "src/main.rs"
